routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
return view('welcome');
});
*/
Route::group(['middleware'=>'language'],function (){
  Route::get('/newsletter-subscription','FrontController@newsletterSubscription')->name('newsletterSubscription');

  Route::get('/map','FrontController@map')->name('map');

  Route::get('/','FrontController@home')->name('home');
  Route::get('/cat/{name}/{id}','FrontController@category')->name('category');
  Route::get('/prod/{name}/{id}','FrontController@product')->name('product');
  Route::get('/art/{name}/{id}','FrontController@article')->name('article');

  Route::post('/calculate-transfer-cost/','FrontController@calculateTransferCost')->name('calculateTransferCost');
  Route::get('/checkout','FrontController@checkout')->name('checkout');
  Route::post('/pay','FrontController@pay')->name('pay');



  Route::post('/add-to-cart','FrontController@addToCart')->name('addToCart');
  Route::get('/remove-from-cart/{id}','FrontController@removeFromCart')->name('removeFromCart');

  Route::get('/thank-you/{id}','FrontController@thankYou')->name('thankYou');

  Route::get('test-distance-calculator/{from}/{to}','RoadController@calculateDistanceBetweenTwoPoints');

  Route::get('contact-us','FrontController@contactUs')->name('contactUs');
  Route::get('experiences','FrontController@experiences')->name('experiences');

  Route::get('set-language/{language}','FrontController@setLanguage')->name('languageSwitcher');

    Route::get('vouchers','FrontController@vouchers')->name('vouchers');
    Route::post('voucher-checkout','FrontController@voucherCheckout')->name('voucherCheckout');

    Route::get('interstitial-page-afterr-adding-to-card/{id}','FrontController@interstitialPageAfterAddingToCart')->name('interstitialPageAfterAddingToCart');


});


Route::post('/admin/media-dropzone', ['uses' => 'MediaController@handleDropzoneUpload']);

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Productaddon;
use App\Models\Article;
use App\Models\Category;
use App\Models\Geofence;
use App\Models\Lead;
use App\Models\Language;
use App\Models\Leadrow;
use App\Models\Voucher;
use App\Models\Menu;
use App\Models\Availability;
use App\Models\Textblock;
use App\Models\Slideshow;
use Mail;
use App\Mail\OrderEmail;
use Cookie;
use Str;
use App;
use Carbon\Carbon;
use Newsletter;
use Illuminate\Support\Facades\Validator;


#use \DrewM\MailChimp\MailChimp;


class FrontController extends Controller
{
    //

    var $cookieDuration = 86400 * 365;

    public function __construct()
    {

        app()->setLocale('en');
    }

    public function newsletterSubscription(Request $request)
    {
        #Newsletter::subscribe('giojkd@gmail.com');
        $email = $request->input('email');
        $date_of_birth = $request->input('date_of_birth');
        $nationality = $request->input('nationality');
        $gender = $request->input('gender');
        $address = json_encode(['state' => 'Florence']);
        $address = 'ciao';
        #dd($request->all());
        #Newsletter::subscribePending($email, ['FNAME'=>'Giovanni', 'LNAME'=>'Orlandi']);
        $date_of_birth = '01/02/2020';
        $nationality = 'Italian';
        $gender = 'Male';
        $result = Newsletter::subscribePending($email, ['DATEOFBIRT' => $date_of_birth, 'NATIONALIT' => $nationality, 'GENDER' => $gender]);
        dd($result);
        echo 'done';

        /*$MailChimp = new MailChimp('7c96f2211d44ad649351a4f0ff80eff3-us19');
        $list_id = 'ac36ff5d2b'; #env('MAILCHIMP_LIST_ID');
        $result = $MailChimp->post("lists/$list_id/members", [
                  'email_address' => 'giojkd@gmail.com',
                  'status'        => 'subscribed',
              ]);

        dd($result);*/

    }

    public function home(Request $request)
    {

#     App::setLocale('it');

        $today = date('Y-m-d');
        $in90Days = date('Y-m-d', strtotime('+90days'));
        $data = [];
        $data['products'] = Product
            ::with([
                'geofence',
                'category',
                'availabilities' => function ($query) use ($today, $in90Days) {
                    $query->whereBetween('day', [$today, $in90Days]);
                }
            ])
            ->where('enabled', 1)
            ->orderBy('created_at', 'DESC')
            ->limit(9)
            ->get();

        $data['categories'] = Category
            ::withCount(['products'])
            ->get();

        $data['geofences'] = Geofence
            ::all();

        $data['menus'] = Menu::with(['articles' => function ($query) {
            $query->orderBy('lft', 'ASC');
        }])->get()->keyBy('slug');
        $data['textBlocks'] = Textblock::all()->pluck('content', 'slug');
        $data['slideshows'] = Slideshow::all()->keyBy('slug');

        #dd($data);
        $data['languages'] = Language::where('is_website_language', 1)->get()->keyBy('iso');
        return view('front.home', $data);
    }

    public function article($name, $id)
    {
        $data = [];
        $data['menus'] = Menu::with(['articles' => function ($query) {
            $query->orderBy('lft', 'ASC');
        }])->get()->keyBy('slug');
        $data['article'] = Article::find($id);
        $data['languages'] = Language::where('is_website_language', 1)->get()->keyBy('iso');
        return view('front.article', $data);
    }

    public function category($name, $id)
    {
        $today = date('Y-m-d');

        $in15Days = date('Y-m-d', strtotime('+15days'));
        $data = [];
        $data['menus'] = Menu::with(['articles' => function ($query) {
            $query->orderBy('lft', 'ASC');
        }])->get()->keyBy('slug');
        $data['category'] = Category::find($id);
        $data['products'] = Product
            ::with([
                'geofence',
                'category',
                'availabilities' => function ($query) use ($today, $in15Days) {
                    $query->whereBetween('day', [$today, $in15Days]);
                }
            ])
            ->whereNotNull('photos')
            ->where('category_id', $id)
            ->where('enabled', 1)
            ->limit(10)
            ->orderBy('updated_at', 'DESC')
            ->orderBy('created_at', 'DESC')
            ->get();
        $data['languages'] = Language::where('is_website_language', 1)->get()->keyBy('iso');
        return view('front.category', $data);
    }

    public function product($name, $id)
    {
        $data = [];



        $today = date('Y-m-d');
        $in90Days = date('Y-m-d', strtotime('+365days'));
        $data = [];
        $data['menus'] = Menu::with(['articles' => function ($query) {
            $query->orderBy('lft', 'ASC');
        }])->get()->keyBy('slug');

        $data['product'] = Product
            ::with([
                'geofence',
                'addons',
                'category',
                'languages',
                'reviews',
                'pricerules',
                'availabilities' => function ($query) use ($today, $in90Days) {
                    $query->whereBetween('day', [$today, $in90Days]);
                }
            ])
            ->where('id', $id)
            ->first();




        $data['similar_products'] = Product
            ::with([
                'geofence',
                'category',
                'availabilities' => function ($query) use ($today, $in90Days) {
                    $query->whereBetween('day', [$today, $in90Days]);
                }
            ])
            ->whereNotNull('photos')
            ->where('category_id', $data['product']->category_id)
            ->where('id', '!=', $data['product']->id)
            ->limit(10)
            ->orderBy('updated_at', 'DESC')
            ->orderBy('created_at', 'DESC')
            ->get();


        $data['languages'] = Language::where('is_website_language', 1)->get()->keyBy('iso');
        #dd($data);
        return view('front.product', $data);
    }


    public function addToCart(Request $request)
    {
        $lead_id = Cookie::get('lead_id');
        if ($lead_id != '') {
            $lead = Lead::find($lead_id);
        } else {
            $lead = Lead::create([]);
            Cookie::queue(Cookie::make('lead_id', $lead->id, $this->cookieDuration));
        }
        $product = Product::findOrFail($request->input('product_id'));
        $date = Carbon::createFromFormat('m/d/Y', $request->input('date'))->format('Y-m-d');
        $availability = Availability
            ::where('product_id', $request->input('product_id'))
            ->where('day', $date)
            ->where('time', $request->input('time') . ':00')
            ->first();
        $totParticipants = $request->input('children') + $request->input('adults');
        $vehiclesCount = ceil($totParticipants / $product->free_transfer_up_to);


        $leadrow = Leadrow
            ::firstOrCreate(
                [
                    'lead_id' => $lead->id,
                    'date' => $date,
                    'time' => $request->input('time') . ':00',
                ]
            );

        #$leadrow->addons->delete();

        $addons = $request->input('input_addons');
        $addonsTotal = 0;
        if ($addons != '') {
            $addons = explode(',', $addons);
            $addonsObjects = Productaddon::find($addons);

            foreach ($addonsObjects as $obj) {

                $addonsTotal += $obj->price_per_adult * $request->input('adults') + $obj->price_per_child * $request->input('children');
            }
        }


        $leadrow->addons()->sync($addons);

        $total =
            $availability->price_per_child * $request->input('children')
            + $availability->price_per_adult * $request->input('adults')
            + ($vehiclesCount * $product->free_transfer)
            + $addonsTotal;

        $leadrow
            ->fill([
                'product_id' => $request->input('product_id'),
                'adults' => $request->input('adults'),
                'children' => $request->input('children'),
                'price_per_adult' => $availability->price_per_adult,
                'price_per_child' => $availability->price_per_child,
                'total' => $total
            ])
            ->save();

        if ($product->interstitial_page_after_adding_to_cart) {
            return redirect(route('interstitialPageAfterAddingToCart', ['id' => $product->id]));
        }

        return redirect(route('checkout'));
    }

    public function removeFromCart($id)
    {
        $leadRow = Leadrow::findOrFail($id);
        $leadRow->delete();
        return redirect(route('checkout'));
    }


    public function calculateTransferCost(Request $request)
    {

        $lead_id = Cookie::get('lead_id');

        if ($lead_id != '') {
            $lead = Lead::find($lead_id);
        } else {
            $lead = Lead::create([]);
            Cookie::queue(Cookie::make('lead_id', $lead->id, $this->cookieDuration));
        }

        $lead->pickup_address_latitude = $request->input('pickup_address_latitude');
        $lead->pickup_address_longitude = $request->input('pickup_address_longitude');
        $lead->pickup_address = $request->input('pickup_address');
        $lead->save();


        $lead->calculateLeadTotals();

        return redirect()->route('checkout');

        exit;

    }

    public function checkout()
    {

        $lead_id = Cookie::get('lead_id');
        if ($lead_id != '') {
            $lead = Lead::find($lead_id);
        } else {
            $lead = Lead::create([]);
            Cookie::queue(Cookie::make('lead_id', $lead->id, $this->cookieDuration));
        }
        $data = [
            'lead' => $lead,
            'rows' => $lead->leadrows()->orderBy('date', 'asc')->orderBy('time', 'asc')->get()
        ];

resources/views/front/article.blade.php
@extends('front.index')

@section('header_jumbotron')
<div class="common-page">
  <div class="jumbotron banner-head">
    <div class="container">

      @include('front/components/common_page_header')

    </div>
  </div> <!-- banner-head -->
</div>
@endsection
@section('page_main')

  <div class="container">
    <div class="col-md-12">
      <div class="pt-4 mt-4">
        <h1>{{$article->name}}</h1>
        {!!$article->content!!}
      </div>
    </div>
  </div>

@endsection

resources/views/front/category.blade.php
@extends('front.index')

@section('header_jumbotron')
<div class="common-page">
  <div class="jumbotron banner-head">
    <div class="container">

      @include('front/components/common_page_header')

    </div>
  </div> <!-- banner-head -->
</div>
@endsection

@section('page_main')

  <div class="container">
    <div class="row my-4 py-4">
      <div class="col-md-12 text-center">
        <h1>{{$category->name}}</h1>
        @if(!is_null($category->description))
        <div class="my-4">
          {!!$category->description!!}
        </div>
        @endif
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        @include('front.components.products_grid')
      </div>
    </div>
  </div>

@endsection

resources/views/front/contact_us.blade.php
@extends('front.index');

@section('header_jumbotron')
  <div class="common-page">
    <div class="jumbotron banner-head">
      <div class="container">

        @include('front/components/common_page_header')

      </div>
    </div> <!-- banner-head -->
  </div>
@endsection
@section('page_main')
  <div class="container">
    <div class="col-md-12">
      <div class="pt-4 mt-4">
        <h1>Contact us</h1>
        <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
        <script>
        hbspt.forms.create({
          portalId: "7230374",
          formId: "288a9698-68c9-42fa-8e9e-9df449c8c229"
        });
        </script>

        <hr>

        <h3 class="mb-3">TALIXO TUSCANY S.R.L.</h3>
        <ul class="list-unstyled">
          <li class="mb-2">Piazza de' Frescobaldi 4, 50125 Firenze</li>
          <li class="mb-2"><a href="tel:+390550208165">Tel: 0550208165</a>
            <li class="mb-2"><a href="mailto:info@talixotuscany.com">eMail: info@talixotuscany.com</a>
              <li>Piva 06950670486</li>
        </ul>



      </div>
    </div>
  </div>
@endsection

resources/views/front/experiences.blade.php
@extends('front.index')

@section('header_jumbotron')
<div class="common-page">
  <div class="jumbotron banner-head">
    <div class="container">

      @include('front/components/common_page_header')

    </div>
  </div> <!-- banner-head -->
</div>
@endsection

@section('page_main')
<div class="container-fluid pt-4">

  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="mb-4">The complete selection of our marvelous experiences</h1>
        @foreach($productGroups as $products)
        <h1>{{$products[0]->category->name}}</h1>
        <div class="row">
          @include('front.components.products_grid')
        </div>
        @endforeach

      </div>
    </div>
  </div>



</div>
@endsection

resources/views/front/home.blade.php
@extends('front.index')

@section('header_jumbotron')

<style media="screen">
@-webkit-keyframes zoom {
  from {
    -webkit-transform: scale(1, 1);
  }
  to {
    -webkit-transform: scale(1.5, 1.5);
  }
}

@keyframes zoom {
  from {
    transform: scale(1, 1);
  }
  to {
    transform: scale(1.5, 1.5);
  }
}

.carousel-inner .carousel-item {
  -webkit-animation: zoom 20s;
  animation: zoom 20s;
}
</style>
<style media="screen">
.slideshowHomepage{

}
.slideshowHomepage .carousel-inner .carousel-item{
  height: 750px;
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>

<div class="position-relative" style=" height: 900px;">

  <div id="carouselExampleControls" class="d-block d-md-none slideshowHomepage carousel carousel-fade slide d-block position-absolute w-100" data-interval="7000" data-ride="carousel">
    <div class="carousel-inner w-100">


      @foreach(array_values(json_decode($slideshows['homepage_main_slider']->files,1)) as $index => $photo)
      <div class="carousel-item @if($index == 0) active @endif w-100" style="background-image: url({{url($photo)}})"></div>

      @endforeach
    </div>

  </div>

<video width="100%" autoplay="autoplay" loop="true" muted class="d-none d-md-block">
  <source src="{{ url('/front/videos/background-video.mp4') }}" type="video/mp4">

Your browser does not support the video tag.
</video>
  <div class="jumbotron banner-head" style="z-index: 999; position: absolute; top: 0px; left: 0px; width: 100%; background: transparent;">
    <div class="container">
      <header>
        <div class="logo">
          <a href="{{route('home')}}">
            <img src="{{asset('front/images/talixo-logo.png')}}">
          </a>
        </div>
        <!--
        <div class="search-bar">
        <div class="form-group search-web">
        <input type="text" class="form-control" placeholder="Cerca">
      </div>
    </div>-->
    <div class="menu-bar">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-sm  navbar-dark">
          <!-- <a class="navbar-brand" href="#">Navbar</a> -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{route('vouchers')}}" class="nav-link special-link">
                        <i class="fa fa-gift"></i> {{ucfirst(__('all.gift'))}}
                    </a>
                </li>
              @foreach($menus['top_menu']->articles as $article)
              <li class="nav-item">
                <a class="nav-link" href="{{$article->getUrl('article')}}">{{$article->name}}</a>
              </li>
              @endforeach
              <li class="nav-item">
                <a class="nav-link" href="{{route('contactUs')}}">{{ucfirst(__('all.contact us'))}}</a>
              </li>
              <li class="nav-item">
                <a href="{{route('experiences')}}" class="nav-link special-link">
                  <i class="fa fa-star"></i> {{ucfirst(__('all.experiences'))}}
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('map')}}" class="nav-link special-link">
                  <i class="fa fa-glass"></i> {{ucfirst(__('all.beyond the label'))}}
                </a>
              </li>


              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{substr($languages[app()->getLocale()]->name,0,3)}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  @foreach($languages as $index => $language)
                    @if($index != app()->getLocale())
                      <a href="{{route('languageSwitcher',['language' => $language->iso])}}" class="dropdown-item" >{{substr($language->name,0,3)}}</a>
                    @endif
                  @endforeach
                </div>
              </li>
              <!--
              <li class="country-symbol"> <span class="currency">€</span> <span class="flag"><img src="/front/images/country.jpg"></span></li>
              <li class="login-registration"> <a href="#">Accedi</a> <a href="#">Registrati</a></li>-->
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </header>

  <div class="explore-amazing">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-5">
          <h2>{{__('all.Explore our amazing selection of unique experiences')}}</h2>
          <div class="search-widget-categories">
            @foreach($categories as $category)
            <a href="{{$category->getUrl('category')}}">{{$category->name}}</a>
            @endforeach
          </div>
          <!--<div class="form-group search-place"> <input type="text" class="form-control" placeholder="Where are you going ?"> </div>

          <div class="form-group calendar-new">
          <div class='input-group date' id='checkin'>
          <input type='text' class="form-control"  placeholder="Check in - Check out " />
          <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>

    <div class="form-group people-place"> <input type="text" class="form-control" placeholder="2 Adulti  -  0 Bambini"> </div>

    <div class="search-place"> <input type="submit" value="Cerca"> </div>-->
  </div>
</div>
</div>
</div><!-- explore-amazing -->

</div>
</div> <!-- banner-head -->
</div>
@endsection

@section('page_main')
<div class="container">

  <div class="col-sm-12 company-features">
    <div class="row">
      <div class="col-sm-3 company-features-inner">
        <img src="/front/images/year-icon.png">
        <div class="company-inner-data">
          <h3 data-slug="homepage_box_1_slug">{{$textBlocks['homepage_box_1_slug']}}</h3>
          <p data-slug="homepage_box_1_content">{{$textBlocks['homepage_box_1_content']}}</p>
        </div><!-- company-inner-data -->
      </div>
      <div class="col-sm-3 company-features-inner">
        <img src="/front/images/partner-icon.png">
        <div class="company-inner-data">
          <h3 data-slug="homepage_box_2_slug">{{$textBlocks['homepage_box_2_slug']}}</h3>
          <p data-slug="homepage_box_2_content">{{$textBlocks['homepage_box_2_content']}}</p>
        </div><!-- company-inner-data -->
      </div>
      <div class="col-sm-3 company-features-inner">
        <img src="/front/images/exp-icon.png">
        <div class="company-inner-data">
          <h3 data-slug="homepage_box_3_slug">{{$textBlocks['homepage_box_3_slug']}}</h3>
          <p data-slug="homepage_box_3_content">{{$textBlocks['homepage_box_3_content']}}</p>
        </div><!-- company-inner-data -->
      </div>
      <div class="col-sm-3 company-features-inner">
        <img src="/front/images/customize_icon.png">
        <div class="company-inner-data">
          <h3 data-slug="homepage_box_4_slug">{{$textBlocks['homepage_box_4_slug']}}</h3>
          <p data-slug="homepage_box_4_content">{{$textBlocks['homepage_box_4_content']}}</p>
        </div><!-- company-inner-data -->
      </div>
    </div>
  </div><!-- col-sm-12  company-features -->


  <div class="col-sm-12 discover-experience-head">
    <div class="row">
      <div class="col-sm-12 discover-experience-inner">
        <h2 data-slug="homepage_caption_1_title">{{$textBlocks['homepage_caption_1_title']}}</h2>
        <p data-slug="homepage_caption_1_content">{{$textBlocks['homepage_caption_1_content']}}</p>
      </div>
    </div>
  </div><!-- discover-experience-head -->

  @include('front.components.products_grid')

    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-12 text-center">
                <a href="{{route('experiences')}}" class="btn-talixo-light d-inline-block" style="width: auto!important;">Show more opportunities</a>
            </div>
        </div>
    </div>


  <!-- col-sm-12  discover-experience-main -->

</div><!-- container -->
@endsection

@section('adv_banner')
<!--
<div class="custom-travel-main">
<div class="container">
<div class="col-sm-12">
<div class="row">
<div class="col-sm-4">
<div class="red-area">
<p>CUSTOMIZE</p>
<p class="your-half">YOUR</p>
<p>TRAVEL</p>
</div>
<a class="grey-btn" href="#">Design your dream travel <span> &gt; </span></a>
</div>
</div>
</div>
</div>
</div>-->
@endsection


@section('pre_footer')

<div style="height: 100px; width: 100%;"></div>

<div class="container" >
  <div class="col-sm-12 discover-experience-head inspiration-head">
    <div class="row">
      <div class="col-sm-12 discover-experience-inner">
        <h2 data-slug="homepage_caption_2_title">{{$textBlocks['homepage_caption_2_title']}}</h2>
        <p data-slug="homepage_caption_2_content">{{$textBlocks['homepage_caption_2_content']}}</p>
      </div>
    </div>
  </div><!-- discover-experience-head -->

  <div class="col-sm-12 inspiration-travel">
    <div class="row">
      @foreach($categories as $index => $category)
      @if($index < 6)
      <div class="col-sm-4">

        <a href="{{$category->getUrl('category')}}" class="inspiration-travel-inner" style="background:url('/{{$category->cover}}') no-repeat center center;">
          <div class="inspiration-travel-inner-banner">
            <span>{{$category->name}}</span>
          </div>
          <p>{{$category->products_count}} {{__('all.experiences')}}</p>
        </div>

      </a>
      @endif
      @endforeach
      <!--
      <div class="col-sm-4 inspiration-travel-inner">
      <img src="/front/images/dine_me.png">
      <p>93 experiences</p>
    </div>

    <div class="col-sm-4 inspiration-travel-inner">
    <img src="/front/images/museums.png">
    <p>53 experiences</p>
  </div>

  <div class="col-sm-4 inspiration-travel-inner">
  <img src="/front/images/dine_me_2.png">
  <p>93 experiences</p>
</div>

<div class="col-sm-4 inspiration-travel-inner cross1">
<img src="/front/images/museums_2.png">
<p>53 experiences</p>
</div>

<div class="col-sm-4 inspiration-travel-inner cross2">
<img src="/front/images/bike_tour_2.png">
<p>23 experiences</p>
</div>-->
</div>
</div><!-- inspiration-travel -->


@if(($categories->count()-6) > 0)
<div class="col-sm-12 suggestion-tag">
  <div class="row">
    @foreach($categories->splice(6)->chunk(3) as $index =>  $categories_chunk)
    <ul>
      @foreach($categories_chunk as $category)
      <li> <a href="{{$category->getUrl('category')}}"> {{$category->name}} </a> </li>
      @endforeach
    </ul>
    @endforeach
    <!--<p class="grey-btn-area-para"><a class="grey-btn" href="#">Discover over 50 suggestioons <span> &gt; </span></a></p>-->
  </div>
</div><!-- suggestion-tag -->
@endif
</div><!-- container -->

@endsection

@push('footer_scripts')

@endpush

resources/views/front/interstitial_page.blade.php
@extends('front.index')

@section('header_jumbotron')
    <div class="common-page">
        <div class="jumbotron banner-head">
            <div class="container">

                @include('front/components/common_page_header')

            </div>
        </div> <!-- banner-head -->
    </div>
@endsection

@section('page_main')

    <div class="container">
        <div class="row my-4 py-4">
            <div class="col-md-12 text-center">
                <h1>Now that you have added {{$added_product->name}} to your trip...</h1>
                <div class="my-4">
                    Enrich your experience by continuing your trip with one of the following experiences...
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @include('front.components.products_grid')
            </div>
        </div>
    </div>

@endsection

resources/views/front/thank_you.blade.php
@extends('front.index');

@section('header_jumbotron')
<div class="common-page">
  <div class="jumbotron banner-head">
    <div class="container">

      @include('front/components/common_page_header')

    </div>
  </div> <!-- banner-head -->
</div>
@endsection

@section('page_main')

  <div class="container">
    <div class="row my-4 py-4">
      <div class="col-md-12 text-center">
        <h1>Thank you!</h1>
        <p>
          Thank your for your purchase!
        </p>
      </div>
    </div>
  </div>

@endsection